// these are sample guides which Oscar should put in the actual guides
const guides = {
	guide1:
		"Guide 1: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in odio pulvinar, mollis enim aliquet, lacinia ex. Curabitur erat lorem, pretium nec ex quis, consequat convallis purus. Donec est tellus, molestie sed erat in, sollicitudin facilisis augue. Suspendisse condimentum lectus ac congue aliquam. Pellentesque fermentum congue metus. Cras eu feugiat purus. Suspendisse varius at magna quis consectetur. Nam sagittis rhoncus fermentum. Ut eu massa a quam semper porta sit amet eu est. Duis rhoncus venenatis libero vitae fermentum. Ut finibus magna est, et luctus justo venenatis ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras eget mauris non justo auctor scelerisque ut at enim. Nulla id nibh vitae est placerat congue non a urna. Morbi aliquam mauris id pulvinar imperdiet. Vivamus id lorem quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac turpis faucibus, fringilla nisl id, auctor sapien. Aliquam in tortor molestie, venenatis elit eu, interdum purus. Vivamus scelerisque erat tellus, a feugiat diam varius vitae. Ut vitae turpis ut libero lacinia semper. Curabitur nulla ante, porta a ipsum et, ornare tristique mauris. Nunc et sem a ligula placerat dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam semper orci non risus auctor pretium. Aenean in lacinia erat. Etiam fringilla massa mauris, eget laoreet libero vulputate ac. Nam hendrerit ullamcorper nulla non sollicitudin. Integer quis porttitor metus.",
	guide2:
		"Guide 2: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in odio pulvinar, mollis enim aliquet, lacinia ex. Curabitur erat lorem, pretium nec ex quis, consequat convallis purus. Donec est tellus, molestie sed erat in, sollicitudin facilisis augue. Suspendisse condimentum lectus ac congue aliquam. Pellentesque fermentum congue metus. Cras eu feugiat purus. Suspendisse varius at magna quis consectetur. Nam sagittis rhoncus fermentum. Ut eu massa a quam semper porta sit amet eu est. Duis rhoncus venenatis libero vitae fermentum. Ut finibus magna est, et luctus justo venenatis ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras eget mauris non justo auctor scelerisque ut at enim. Nulla id nibh vitae est placerat congue non a urna. Morbi aliquam mauris id pulvinar imperdiet. Vivamus id lorem quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac turpis faucibus, fringilla nisl id, auctor sapien. Aliquam in tortor molestie, venenatis elit eu, interdum purus. Vivamus scelerisque erat tellus, a feugiat diam varius vitae. Ut vitae turpis ut libero lacinia semper. Curabitur nulla ante, porta a ipsum et, ornare tristique mauris. Nunc et sem a ligula placerat dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam semper orci non risus auctor pretium. Aenean in lacinia erat. Etiam fringilla massa mauris, eget laoreet libero vulputate ac. Nam hendrerit ullamcorper nulla non sollicitudin. Integer quis porttitor metus.",
	guide3:
		"Guide 3: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in odio pulvinar, mollis enim aliquet, lacinia ex. Curabitur erat lorem, pretium nec ex quis, consequat convallis purus. Donec est tellus, molestie sed erat in, sollicitudin facilisis augue. Suspendisse condimentum lectus ac congue aliquam. Pellentesque fermentum congue metus. Cras eu feugiat purus. Suspendisse varius at magna quis consectetur. Nam sagittis rhoncus fermentum. Ut eu massa a quam semper porta sit amet eu est. Duis rhoncus venenatis libero vitae fermentum. Ut finibus magna est, et luctus justo venenatis ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras eget mauris non justo auctor scelerisque ut at enim. Nulla id nibh vitae est placerat congue non a urna. Morbi aliquam mauris id pulvinar imperdiet. Vivamus id lorem quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac turpis faucibus, fringilla nisl id, auctor sapien. Aliquam in tortor molestie, venenatis elit eu, interdum purus. Vivamus scelerisque erat tellus, a feugiat diam varius vitae. Ut vitae turpis ut libero lacinia semper. Curabitur nulla ante, porta a ipsum et, ornare tristique mauris. Nunc et sem a ligula placerat dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam semper orci non risus auctor pretium. Aenean in lacinia erat. Etiam fringilla massa mauris, eget laoreet libero vulputate ac. Nam hendrerit ullamcorper nulla non sollicitudin. Integer quis porttitor metus.",
	guide4:
		"Guide 4: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in odio pulvinar, mollis enim aliquet, lacinia ex. Curabitur erat lorem, pretium nec ex quis, consequat convallis purus. Donec est tellus, molestie sed erat in, sollicitudin facilisis augue. Suspendisse condimentum lectus ac congue aliquam. Pellentesque fermentum congue metus. Cras eu feugiat purus. Suspendisse varius at magna quis consectetur. Nam sagittis rhoncus fermentum. Ut eu massa a quam semper porta sit amet eu est. Duis rhoncus venenatis libero vitae fermentum. Ut finibus magna est, et luctus justo venenatis ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras eget mauris non justo auctor scelerisque ut at enim. Nulla id nibh vitae est placerat congue non a urna. Morbi aliquam mauris id pulvinar imperdiet. Vivamus id lorem quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac turpis faucibus, fringilla nisl id, auctor sapien. Aliquam in tortor molestie, venenatis elit eu, interdum purus. Vivamus scelerisque erat tellus, a feugiat diam varius vitae. Ut vitae turpis ut libero lacinia semper. Curabitur nulla ante, porta a ipsum et, ornare tristique mauris. Nunc et sem a ligula placerat dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam semper orci non risus auctor pretium. Aenean in lacinia erat. Etiam fringilla massa mauris, eget laoreet libero vulputate ac. Nam hendrerit ullamcorper nulla non sollicitudin. Integer quis porttitor metus.",
	guide5:
		"Guide 5: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in odio pulvinar, mollis enim aliquet, lacinia ex. Curabitur erat lorem, pretium nec ex quis, consequat convallis purus. Donec est tellus, molestie sed erat in, sollicitudin facilisis augue. Suspendisse condimentum lectus ac congue aliquam. Pellentesque fermentum congue metus. Cras eu feugiat purus. Suspendisse varius at magna quis consectetur. Nam sagittis rhoncus fermentum. Ut eu massa a quam semper porta sit amet eu est. Duis rhoncus venenatis libero vitae fermentum. Ut finibus magna est, et luctus justo venenatis ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras eget mauris non justo auctor scelerisque ut at enim. Nulla id nibh vitae est placerat congue non a urna. Morbi aliquam mauris id pulvinar imperdiet. Vivamus id lorem quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac turpis faucibus, fringilla nisl id, auctor sapien. Aliquam in tortor molestie, venenatis elit eu, interdum purus. Vivamus scelerisque erat tellus, a feugiat diam varius vitae. Ut vitae turpis ut libero lacinia semper. Curabitur nulla ante, porta a ipsum et, ornare tristique mauris. Nunc et sem a ligula placerat dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam semper orci non risus auctor pretium. Aenean in lacinia erat. Etiam fringilla massa mauris, eget laoreet libero vulputate ac. Nam hendrerit ullamcorper nulla non sollicitudin. Integer quis porttitor metus.",
	guide6:
		"Guide 6: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in odio pulvinar, mollis enim aliquet, lacinia ex. Curabitur erat lorem, pretium nec ex quis, consequat convallis purus. Donec est tellus, molestie sed erat in, sollicitudin facilisis augue. Suspendisse condimentum lectus ac congue aliquam. Pellentesque fermentum congue metus. Cras eu feugiat purus. Suspendisse varius at magna quis consectetur. Nam sagittis rhoncus fermentum. Ut eu massa a quam semper porta sit amet eu est. Duis rhoncus venenatis libero vitae fermentum. Ut finibus magna est, et luctus justo venenatis ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras eget mauris non justo auctor scelerisque ut at enim. Nulla id nibh vitae est placerat congue non a urna. Morbi aliquam mauris id pulvinar imperdiet. Vivamus id lorem quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac turpis faucibus, fringilla nisl id, auctor sapien. Aliquam in tortor molestie, venenatis elit eu, interdum purus. Vivamus scelerisque erat tellus, a feugiat diam varius vitae. Ut vitae turpis ut libero lacinia semper. Curabitur nulla ante, porta a ipsum et, ornare tristique mauris. Nunc et sem a ligula placerat dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam semper orci non risus auctor pretium. Aenean in lacinia erat. Etiam fringilla massa mauris, eget laoreet libero vulputate ac. Nam hendrerit ullamcorper nulla non sollicitudin. Integer quis porttitor metus.",
	guide7:
		"Guide 7: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in odio pulvinar, mollis enim aliquet, lacinia ex. Curabitur erat lorem, pretium nec ex quis, consequat convallis purus. Donec est tellus, molestie sed erat in, sollicitudin facilisis augue. Suspendisse condimentum lectus ac congue aliquam. Pellentesque fermentum congue metus. Cras eu feugiat purus. Suspendisse varius at magna quis consectetur. Nam sagittis rhoncus fermentum. Ut eu massa a quam semper porta sit amet eu est. Duis rhoncus venenatis libero vitae fermentum. Ut finibus magna est, et luctus justo venenatis ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras eget mauris non justo auctor scelerisque ut at enim. Nulla id nibh vitae est placerat congue non a urna. Morbi aliquam mauris id pulvinar imperdiet. Vivamus id lorem quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac turpis faucibus, fringilla nisl id, auctor sapien. Aliquam in tortor molestie, venenatis elit eu, interdum purus. Vivamus scelerisque erat tellus, a feugiat diam varius vitae. Ut vitae turpis ut libero lacinia semper. Curabitur nulla ante, porta a ipsum et, ornare tristique mauris. Nunc et sem a ligula placerat dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam semper orci non risus auctor pretium. Aenean in lacinia erat. Etiam fringilla massa mauris, eget laoreet libero vulputate ac. Nam hendrerit ullamcorper nulla non sollicitudin. Integer quis porttitor metus.",
	guide8:
		"Guide 8: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in odio pulvinar, mollis enim aliquet, lacinia ex. Curabitur erat lorem, pretium nec ex quis, consequat convallis purus. Donec est tellus, molestie sed erat in, sollicitudin facilisis augue. Suspendisse condimentum lectus ac congue aliquam. Pellentesque fermentum congue metus. Cras eu feugiat purus. Suspendisse varius at magna quis consectetur. Nam sagittis rhoncus fermentum. Ut eu massa a quam semper porta sit amet eu est. Duis rhoncus venenatis libero vitae fermentum. Ut finibus magna est, et luctus justo venenatis ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras eget mauris non justo auctor scelerisque ut at enim. Nulla id nibh vitae est placerat congue non a urna. Morbi aliquam mauris id pulvinar imperdiet. Vivamus id lorem quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac turpis faucibus, fringilla nisl id, auctor sapien. Aliquam in tortor molestie, venenatis elit eu, interdum purus. Vivamus scelerisque erat tellus, a feugiat diam varius vitae. Ut vitae turpis ut libero lacinia semper. Curabitur nulla ante, porta a ipsum et, ornare tristique mauris. Nunc et sem a ligula placerat dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam semper orci non risus auctor pretium. Aenean in lacinia erat. Etiam fringilla massa mauris, eget laoreet libero vulputate ac. Nam hendrerit ullamcorper nulla non sollicitudin. Integer quis porttitor metus.",
	guide9:
		"Guide 9: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in odio pulvinar, mollis enim aliquet, lacinia ex. Curabitur erat lorem, pretium nec ex quis, consequat convallis purus. Donec est tellus, molestie sed erat in, sollicitudin facilisis augue. Suspendisse condimentum lectus ac congue aliquam. Pellentesque fermentum congue metus. Cras eu feugiat purus. Suspendisse varius at magna quis consectetur. Nam sagittis rhoncus fermentum. Ut eu massa a quam semper porta sit amet eu est. Duis rhoncus venenatis libero vitae fermentum. Ut finibus magna est, et luctus justo venenatis ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras eget mauris non justo auctor scelerisque ut at enim. Nulla id nibh vitae est placerat congue non a urna. Morbi aliquam mauris id pulvinar imperdiet. Vivamus id lorem quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac turpis faucibus, fringilla nisl id, auctor sapien. Aliquam in tortor molestie, venenatis elit eu, interdum purus. Vivamus scelerisque erat tellus, a feugiat diam varius vitae. Ut vitae turpis ut libero lacinia semper. Curabitur nulla ante, porta a ipsum et, ornare tristique mauris. Nunc et sem a ligula placerat dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam semper orci non risus auctor pretium. Aenean in lacinia erat. Etiam fringilla massa mauris, eget laoreet libero vulputate ac. Nam hendrerit ullamcorper nulla non sollicitudin. Integer quis porttitor metus.",
	localSetting:
		"Local Setting: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in odio pulvinar, mollis enim aliquet, lacinia ex. Curabitur erat lorem, pretium nec ex quis, consequat convallis purus. Donec est tellus, molestie sed erat in, sollicitudin facilisis augue. Suspendisse condimentum lectus ac congue aliquam. Pellentesque fermentum congue metus. Cras eu feugiat purus. Suspendisse varius at magna quis consectetur. Nam sagittis rhoncus fermentum. Ut eu massa a quam semper porta sit amet eu est. Duis rhoncus venenatis libero vitae fermentum. Ut finibus magna est, et luctus justo venenatis ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras eget mauris non justo auctor scelerisque ut at enim. Nulla id nibh vitae est placerat congue non a urna. Morbi aliquam mauris id pulvinar imperdiet. Vivamus id lorem quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac turpis faucibus, fringilla nisl id, auctor sapien. Aliquam in tortor molestie, venenatis elit eu, interdum purus. Vivamus scelerisque erat tellus, a feugiat diam varius vitae. Ut vitae turpis ut libero lacinia semper. Curabitur nulla ante, porta a ipsum et, ornare tristique mauris. Nunc et sem a ligula placerat dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam semper orci non risus auctor pretium. Aenean in lacinia erat. Etiam fringilla massa mauris, eget laoreet libero vulputate ac. Nam hendrerit ullamcorper nulla non sollicitudin. Integer quis porttitor metus.",
};

// credit for Developers
const creditDevelopers = [
	"Programming, Design and Management - Oscar Liang",
	"Programming and Design- Tommy Chen",
];
// credit for Wallpapers
const creditWallpapers = [
	"Sunset by AxiomDesign",
	"Forest by Mikael Gustafsson",
	"Cityscape by Louis Coyle",
	"Rainy by slippypenguin",
	"Blocks by Foxerbit",
	"Paint by Foxerbit",
	"Moon by ProductAdda",
	"Valley by Foxerbit",
	"Train by nyaoayn",
];
// credit for Scripts
const creditScripts = [
	"FitText by davatron5000",
	"Js-Cookie by Michael De Boey",
];
